services:
  weaponsforge.vitexperiments:
    container_name: weaponsforge-vitexperiments
    image: weaponsforge/vitexperiments:latest
    env_file:
      - ./app/.env
    build:
      context: ./app
      dockerfile: Dockerfile
      target: development
    networks:
      - weaponsforge-vitexperiments
    volumes:
      - ./app/:/opt/app
      - /opt/app/node_modules
    ports:
      - "3000:3000"     # React app web server
      - "4173:4173"     # vitest --ui web server
      - "51204:51204"   # vitest ui reports preview web server

networks:
  weaponsforge-vitexperiments:
    name: weaponsforge-vitexperiments
    external: false
