services:
  weaponsforge.vitexperiments:
    container_name: weaponsforge-vitexperiments
    image: weaponsforge/vitexperiments:latest
    env_file:
      - ./app/.env
    build:
      context: ./app
      dockerfile: Dockerfile
      target: development
    networks:
      - weaponsforge-vitexperiments
    volumes:
      - ./app/:/opt/app
      - /opt/app/node_modules
    ports:
      - "3000:3000"

networks:
  weaponsforge-vitexperiments:
    name: weaponsforge-vitexperiments
    external: false
