name: Deploy to Development Environment

# Deploy to Firebase Hosting

on:
  push:
    branches-ignore:
      - main
    # branches:
    #  - dev

jobs:
  lint-client:
    name: Lint and Export client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Use NodeJS v20.15.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0
      - name: Install Dependencies
        run: |
          cd app
          npm install
      - name: Lint
        run: |
          cd app
          npm run lint
      - name: Export static files
        run: |
          cd app
          npm run docker:build
      - name: Prepare Firebase Deployment
        run: |
          cd app
          sed -i -e "s/<FIREBASE_PROJECT>/${{ secrets.FIREBASE_PROJECT }}/g" .firebaserc
          sed -i -e "s/<FIREBASE_HOSTING>/${{ secrets.FIREBASE_HOSTING }}/g" .firebaserc
      - name: Archive Development Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-out
          include-hidden-files: true
          path: |
            app/dist
            app/.firebaserc
            app/firebase.json
          retention-days: 3

  deploy-client:
    name: Deploy Client to Firebase Hosting
    needs: lint-client
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dev-out
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
