name: Deploy to Development Environment

# Deploy to Firebase Hosting

on:
  push:
    branches:
      - dev

jobs:
  lint-export-app:
    name: Lint and Export client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Use NodeJS v20.15.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0
      - name: Install Dependencies
        run: |
          cd app
          npm install
      - name: Lint
        run: |
          cd app
          npm run lint
      - name: Export static files
        run: |
          cd app
          npm run docker:build
      - name: Prepare Firebase Deployment
        run: |
          cd app
          sed -i -e "s/<FIREBASE_PROJECT>/${{ secrets.FIREBASE_PROJECT }}/g" .firebaserc
          sed -i -e "s/<FIREBASE_HOSTING>/${{ secrets.FIREBASE_HOSTING }}/g" .firebaserc
      - name: Archive Development Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-out
          include-hidden-files: true
          path: |
            app/dist
            app/.firebaserc
            app/firebase.json
          retention-days: 3

  test-app:
    name: Unit Tests
    needs: lint-export-app
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use NodeJS v20.15.0
        uses: actions/setup-node@v4
        with:
          node-version: v20.15.0
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: |
          cd app
          npm install

      - name: Test
        run: |
          cd app
          npm test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/html/junit.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: app/html/junit.xml
          check_name: "Test Results"

  deploy-client:
    name: Deploy Client to Firebase Hosting
    needs: [lint-export-app, test-app]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dev-out
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
