name: Run CI Tests

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  lint-app:
    name: Lint and Transpile App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use NodeJS v20.15.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: |
          cd app
          npm install

      - name: Lint
        run: |
          cd app
          npm run lint

      - name: Transpile
        run: |
          cd app
          npx tsc

  test-app:
    name: Unit Tests
    needs: lint-app
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use NodeJS v20.15.0
        uses: actions/setup-node@v4
        with:
          node-version: v20.15.0
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: |
          cd app
          npm install

      - name: Test
        run: |
          cd app
          npm test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/html/junit.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: app/html/junit.xml
          check_name: "Test Results"
